### PR TITLE
Feature classification

### PR DESCRIPTION
**Pull request by rogerkuou**
Add a new function for adding new feature to point cloud
Changes for classification.

### CODE REVIEW

**Comment by rogerkuou** [comment]
Hi @meiertgrootes and @fnattino , I have added the unit test to my part. Would like to review my change? I think dome of the auto checks are failing. But this is due to the test of read/write laz data. Not sure what is causing this since I did not change the relevant file . But I also see the `development` branch is also failing.
Should we fix this one later?

**Comment by fnattino** [comment]
Hi @rogerkuou , you are right there is something wrong with pylas already on the development branch. I will have a look at it right now!

**Comment by fnattino** [comment]
@rogerkuou , the issues were actually two, none of which related to this feature branch. The first was a bug is a test, which is now fixed. The second was probably triggered by an update in lazperf (lazperf from PyPI failed if used with numpy from Conda on python 3.5), it is now circumvented by getting both lazperf and numpy from PyPI in the travis build.

**Comment by meiertgrootes** [comment]
@fnattino @rogerkuou If we have this degree of version dependency should be pin the versions for the requirements file?

**Comment by fnattino** [comment]
@meiertgrootes the problem seems to be only there with python 3.5 - we could set as a requirement python>=3.6

**Comment by meiertgrootes** [comment]
@fnattino Fair enough. 3.6 is fine I'd think.

**Pull request merged**
